arch:
  - arm64

addons:
  hosts:
    - node1

scripts:

  - cd ../
  - wget https://www.openssl.org/source/old/1.1.1/openssl-1.1.1a.tar.gz
  - tar -zxf openssl-1.1.1a.tar.gz
  - cd openssl-1.1.1a
  - sudo ./config -d -Wl,-rpath,/usr/local/lib
  - sudo make -j20
  - sudo make install -j20

  - cd ../
  - wget https://github.com/kunpengcompute/KAEdriver/releases/download/v1.2.8-beta.1/Kunpeng_KAE_driver-1.2.8-beta.1.tar.gz
  - tar -zxf Kunpeng_KAE_driver-1.2.8-bata.1.tar.gz
  - cd Kunpeng_KAE_driver/warpdrive
  - sudo sh autogen.sh 
  - sudo ./configure 
  - sudo make 
  - sudo make install
  
  - cd ../../KAE
  - sudo chmod +x configure
  - sudo ./configure
  - sudo make clean
  - sudo make
  